### ISSUE TITLE
How to increase the pulse count?

### ISSUE THREAD

**Issue by pradweep** [regexident/Pulsar#11]
Hi @regexident ,

Fist of all thank you for your awesome library for pulsar animation. But i am curious to know how to increase the ripple count, is there any property i need to access for increasing the ripple count.

Thanks & Cheers.
Pradeep Kumar

**Comment by regexident** [comment]
Reducing the [`.duration`](https://github.com/regexident/Pulsar/blob/5a5df8ec375ee688e6bc17005b782c48a7c2304f/Pulsar/Classes/Pulse.swift#L19) will increase the pulse frequency.
If you want multiple pulses at the same time you will have to add multiple pulses.
