### ISSUE TITLE
Controlling pulse ripple distance 

### ISSUE THREAD

**Issue by dfeler** [regexident/Pulsar#12]
Hi, I appreciate you making this library, how can I control the distance of the pulse? I need the pulse ripples to not go so far off.

To clarify the circumference of the ripple expands too far outwards - I need it to expand a bit less before disappearing.

Thank you.

**Comment by regexident** [comment]
Hi Daniel,

you should be able to customize `Pulse.transformAfter` something along these lines:

```swift
layer.addPulse { pulse in
    let frame = pulse.frame
    let customScale: CGFloat = 2.0
    let centerPoint = CGPoint(x: frame.midX, y: frame.midY)
    var transform = CATransform3DIdentity
    transform = CATransform3DTranslate(transform, centerPoint.x, centerPoint.y, 0.0)
    transform = CATransform3DScale(transform, customScale, customScale, 1.0)
    transform = CATransform3DTranslate(transform, -centerPoint.x, -centerPoint.y, 0.0)
    pulse.transformAfter = transform

    // ...
}
```

By adjusting `customScale` you adjust the "ripple distance". A scale of `2.0` produces a ripple that ends up being twice as large as the original layer.

That said haven't touched the project in years and am not actively maintaining it any more. Glad you still find it useful though.

**Comment by dfeler** [comment]
Thank you again.
