### ISSUE TITLE
Can I use it in Objective-C project?

### ISSUE THREAD

**Issue by billy84** [regexident/Pulsar#2]
Hi @regexident 

How are you?
Thanks for your supporting great Pulsar.
By the way, I have an Objective-C project but I can't use Pod because there are some reasons.
Can I use it on Objective-C project by manual import?

Please let me know if possible.

Hope to hear from you soon.

Regards,
Billy

**Comment by regexident** [comment]
Hi Billy,

thanks for the kind words. :smile:

Pulsar works fine with [CocoaPods](https://github.com/CocoaPods/CocoaPods), [Carthage](https://github.com/Carthage/Carthage), [Punic](https://github.com/schwa/punic) or even manual linking (via sub-project in `.xcworkspace`). Pick your favorite.

I haven't tried linking against Pulsar from an Objective-C codebase myself. Why don't you just try it? Doesn't take more than 3 minutes.

**Comment by regexident** [comment]
Closing this due to lack of response from OP.
