### ISSUE TITLE
stops after swithc app to background 

### ISSUE THREAD

**Issue by bizibizi** [regexident/Pulsar#4]

**Comment by regexident** [comment]
Hi,

without some more context and information on what you're trying to achieve and/or what's not working there's little I can do to help you.

**Comment by bizibizi** [comment]
i implemented Pulsar, I launched it, i switch app to background, I bring app to foreground, Pulsar stopped

**Comment by regexident** [comment]
I just added support for pause/resume/auto-resume of animations with https://github.com/regexident/Pulsar/commit/5a5df8ec375ee688e6bc17005b782c48a7c2304f.

However auto-resume doesn't seem to work when returning from background and I don't have capacity to spend any more time on this right now.

PRs welcome.

**Comment by bizibizi** [comment]
I added notifications for active app state change and restart pulsing on this notification
