### ISSUE TITLE
update to the latest version of swift please :)

### ISSUE THREAD

**Issue by vitalrum** [regexident/Pulsar#6]
update to the latest version of swift please :)

**Comment by regexident** [comment]
See 2.0.5

**Comment by jaltreuter** [comment]
@regexident 2.0.5 is beyond the head of master and not part of any branch - do you consider it stable?  Also do you plan to update the version used by Cocoapods (it's still back at 2.0.0: https://github.com/CocoaPods/Specs/blob/master/Specs/b/3/a/Pulsar/2.0.0/Pulsar.podspec.json)
